'use client';
import {useState} from 'react';
import {id} from '../../lib/life/model';
export function PageTitle({eyebrow,title,description,action}){return <header className="life-heading"><div><span>{eyebrow}</span><h1>{title}</h1>{description&&<p>{description}</p>}</div>{action}</header>;}
export function Empty({children}){return <p className="life-empty">{children}</p>;}
export function Stats({items}){return <div className="life-stats">{items.map(([label,value])=><div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div>;}
export function Editor({fields,initial,onSave,onCancel,validate,submit='Save',children}){
 const [form,setForm]=useState(initial||{}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 return <form className="life-editor" onSubmit={async e=>{e.preventDefault();const message=validate?.(form);if(message){setError(message);return;}setBusy(true);try{await onSave({...form,id:form.id||id()});}catch(err){setError(err.message||'Could not save. Your input is still here.');}finally{setBusy(false);}}}><div className="life-form-grid">{fields.map(field=><label key={field.key} className={field.type==='textarea'?'wide':''}><span>{field.label}{field.required?' *':''}</span>{field.type==='select'?<select required={field.required} value={form[field.key]??''} onChange={e=>setForm({...form,[field.key]:e.target.value})}>{field.options.map(option=>{const [value,label]=Array.isArray(option)?option:[option,option];return <option key={value} value={value}>{label}</option>;})}</select>:field.type==='textarea'?<textarea rows={3} maxLength={field.maxLength||2000} required={field.required} value={form[field.key]??''} onChange={e=>setForm({...form,[field.key]:e.target.value})}/>:<input type={field.type||'text'} required={field.required} min={field.min} max={field.max} step={field.step} maxLength={field.maxLength||200} value={form[field.key]??''} onChange={e=>setForm({...form,[field.key]:e.target.value})}/>}</label>)}</div>{children}{error&&<p role="alert" className="life-error">{error}</p>}<div className="life-form-actions">{onCancel&&<button type="button" onClick={onCancel}>Cancel</button>}<button className="primary" disabled={busy}>{busy?'Saving…':submit}</button></div></form>;
}
export function RecordActions({onEdit,onDelete,label}){return <div className="life-actions"><button onClick={onEdit} aria-label={'Edit '+label}>Edit</button><button className="danger" onClick={()=>{if(window.confirm('Delete '+label+'?'))onDelete();}} aria-label={'Delete '+label}>Delete</button></div>;}
export const upsert=(records,item)=>records.some(x=>x.id===item.id)?records.map(x=>x.id===item.id?item:x):[...records,item];
