'use client';
import {useState} from 'react';
import {useLife} from '../../lib/life/hooks';
import {AI_CONFIGS} from '../../lib/ai/configs';
import {PageTitle,Editor,Empty,RecordActions,upsert} from './Common';
export function Memory({coach,compact=false}){const [life,update]=useLife(),[selected,setSelected]=useState(coach||'school'),[editing,setEditing]=useState(null);const active=coach||selected,config=AI_CONFIGS[active];const entries=life.memories.filter(m=>m.coach===active);
 async function change(fn){await update(fn);window.dispatchEvent(new Event('tusk-memory-changed'));}
 const content=<>{!coach&&<div className="life-filter">{Object.values(AI_CONFIGS).map(c=><button key={c.id} className={selected===c.id?'active':''} onClick={()=>{setSelected(c.id);setEditing(null);}}>{c.name}</button>)}</div>}<div className="life-memory-intro"><p>Only details you save here are remembered across visits. {config.name} can use its own enabled memories. Other coaches cannot read them.</p><button className="primary" onClick={()=>setEditing({coach:active,kind:'Goal',text:'',enabled:true})}>Add memory</button></div>{editing&&<Editor key={editing.id||'new'} fields={[{key:'kind',label:'Type',type:'select',options:['Goal','Preference','Constraint']},{key:'text',label:'What should this coach remember?',type:'textarea',required:true,maxLength:500}]} initial={editing} onCancel={()=>setEditing(null)} onSave={async f=>{await change(v=>({...v,memories:upsert(v.memories,{...f,coach:active})}));setEditing(null);}}/>}<div className={compact?'':'life-record-grid'}>{entries.map(memory=><article className="life-card" key={memory.id}><span className="life-tag">{memory.kind}</span><p className="life-notes">{memory.text}</p><label className="life-check"><input type="checkbox" checked={memory.enabled!==false} onChange={e=>{const enabled=e.target.checked;change(v=>({...v,memories:v.memories.map(m=>m.id===memory.id?{...m,enabled}:m)}));}}/>Use in conversations</label><RecordActions label={'memory: '+memory.text.slice(0,50)} onEdit={()=>setEditing(memory)} onDelete={()=>change(v=>({...v,memories:v.memories.filter(m=>m.id!==memory.id)}))}/></article>)}</div>{!entries.length&&<Empty>No saved memories for {config.name}.</Empty>}{entries.length>0&&<button className="danger" onClick={()=>{if(window.confirm('Delete every saved memory for '+config.name+'?'))change(v=>({...v,memories:v.memories.filter(m=>m.coach!==active)}));}}>Delete all {config.name} memories</button>}</>;
 return compact?<details className="coach-access"><summary>Saved goals & preferences ({entries.length})</summary>{content}</details>:<><PageTitle eyebrow="YOUR DETAILS, YOUR CONTROL" title="Coach memory" description="Save, edit, pause or delete the details you want each coach to remember."/>{content}</>;
}
