'use client';
import {useState} from 'react';
import {useLife,useWorkspace} from '../../lib/life/hooks';
import {localDate,addDays,weekStart,schoolBlock,warnings,mins,duration} from '../../lib/life/model';
import {PageTitle,Editor,Empty,RecordActions,upsert,Stats} from './Common';
export function Planner(){
 const [life,update]=useLife(),{school,sports}=useWorkspace();const today=localDate(school.timezone);const [week,setWeek]=useState(weekStart(today)),[editing,setEditing]=useState(null),[showSettings,setShowSettings]=useState(false);
 const days=Array.from({length:7},(_,i)=>addDays(week,i));const plans=life.plans.filter(p=>days.includes(p.date));const issues=warnings(plans,life.settings);
 const fields=[{key:'title',label:'Session or commitment',required:true},{key:'kind',label:'Type',type:'select',options:[['study','Study'],['soccer','Soccer'],['school','School'],['personal','Personal']]},{key:'date',label:'Date',type:'date',required:true},{key:'start',label:'Start',type:'time',required:true},{key:'end',label:'End',type:'time',required:true},{key:'assignmentId',label:'Linked assignment (optional)',type:'select',options:[['','None'],...(school.assignments||[]).filter(a=>a.status!=='completed').map(a=>[a.id,a.title])]},{key:'notes',label:'Intended output / notes',type:'textarea'}];
 return <><PageTitle eyebrow="MAKE ROOM FOR WHAT MATTERS" title="Your week" description="Plan study around school and soccer. All times use your school timezone." action={<button className="primary" onClick={()=>setEditing({title:'',kind:'study',date:today,start:'16:00',end:'16:30',done:false})}>Add a block</button>}/><div className="life-week-controls"><button onClick={()=>setWeek(addDays(week,-7))}>Previous week</button><strong>{week} – {addDays(week,6)}</strong><button onClick={()=>setWeek(addDays(week,7))}>Next week</button><button onClick={()=>setWeek(weekStart(today))}>This week</button><button onClick={()=>setShowSettings(!showSettings)}>Planning settings</button></div>
 {showSettings&&<section className="life-card"><label className="life-check"><input type="checkbox" checked={life.settings.reserveSchool} onChange={e=>{const reserveSchool=e.target.checked;update(v=>({...v,settings:{...v.settings,reserveSchool}}));}}/>Reserve weekday school hours</label><p className="life-muted">A planning default, not a synced school calendar. Turn off for holidays or use individual school blocks.</p><Editor key={String(life.settings.reserveSchool)} fields={[{key:'schoolStart',label:'School starts',type:'time',required:true},{key:'schoolEnd',label:'School ends',type:'time',required:true},{key:'studyLimit',label:'Daily study limit (minutes)',type:'number',min:15,max:600,required:true}]} initial={life.settings} validate={f=>mins(f.schoolEnd)<=mins(f.schoolStart)?'School end must be after start.':null} onSave={f=>{update(v=>({...v,settings:{...v.settings,...f,studyLimit:Number(f.studyLimit)}}));setShowSettings(false);}}/></section>}
 {editing&&<Editor key={editing.id||'new'} fields={fields} initial={editing} validate={f=>mins(f.end)<=mins(f.start)?'End time must be after start time.':null} onSave={f=>{update(v=>({...v,plans:upsert(v.plans,f)}));setEditing(null);}} onCancel={()=>setEditing(null)}/>}
 <Stats items={[["Planned blocks",plans.length],["Study minutes",plans.filter(p=>p.kind==='study').reduce((n,p)=>n+duration(p),0)],["Completed",plans.filter(p=>p.done).length],["Scheduling warnings",issues.length]]}/>
 {issues.length>0&&<div className="life-warning" role="status">{issues.map((issue,i)=><p key={i}>{issue.date}: {issue.text}</p>)}</div>}
 <div className="life-week-grid">{days.map(date=>{const reserved=schoolBlock(date,life.settings);const entries=plans.filter(p=>p.date===date).sort((a,b)=>a.start.localeCompare(b.start));return <section className={'life-day '+(date===today?'is-today':'')} key={date}><h2>{new Date(date+'T12:00:00Z').toLocaleDateString('en-US',{weekday:'short',timeZone:'UTC'})}<span>{date.slice(5)}</span></h2>{reserved&&<div className="life-school-block"><b>School</b><small>{reserved.start}–{reserved.end}</small></div>}{entries.map(plan=><article key={plan.id} className={'life-plan kind-'+plan.kind}><label className="life-check"><input type="checkbox" checked={!!plan.done} onChange={e=>{const done=e.target.checked;update(v=>({...v,plans:v.plans.map(p=>p.id===plan.id?{...p,done}:p)}));}}/><strong>{plan.title}</strong></label><small>{plan.start}–{plan.end} · {plan.kind}</small>{plan.notes&&<p>{plan.notes}</p>}<RecordActions label={plan.title} onEdit={()=>setEditing(plan)} onDelete={()=>update(v=>({...v,plans:v.plans.filter(p=>p.id!==plan.id)}))}/></article>)}{(school.assignments||[]).filter(a=>a.due_date===date&&a.status!=='completed').map(a=><p className="life-deadline" key={a.id}>Due: {a.title}</p>)}{(school.tests||[]).filter(t=>t.date===date).map(t=><p className="life-deadline" key={t.id}>Test: {t.title}{t.time?' · '+t.time:''}</p>)}{(sports.sessions||[]).filter(s=>s.date===date).map(s=><p className="life-muted" key={s.id}>{s.sport} · {s.duration||'?'} min · no time set</p>)}{!entries.length&&!reserved&&<Empty>No blocks planned.</Empty>}<button className="life-add-day" onClick={()=>setEditing({title:'',kind:'study',date,start:'16:00',end:'16:30',done:false})}>+ Add block</button></section>;})}</div><p className="life-muted">Training records without a start time appear as reminders; add a timed block to check conflicts. Completing a study block does not submit or finish its assignment.</p></>;
}
