'use client';
import {useState} from 'react';
import {useLife,useWorkspace} from '../../lib/life/hooks';
import {localDate,passingAccuracy,addDays} from '../../lib/life/model';
import {PageTitle,Editor,Empty,RecordActions,upsert,Stats} from './Common';
const statuses=['Not started','In progress','Done'];
export function IBTracker(){const [life,update]=useLife(),[area,setArea]=useState('All'),[editing,setEditing]=useState(null);const entries=life.ib.filter(x=>area==='All'||x.area===area);const today=localDate();
 const fields=[{key:'area',label:'Component',type:'select',options:['IA','Extended Essay','TOK','CAS']},{key:'subject',label:'Subject / activity'},{key:'title',label:'Milestone',required:true},{key:'due',label:'Your deadline',type:'date'},{key:'status',label:'Progress',type:'select',options:statuses},{key:'evidence',label:'Evidence or document link',type:'url'},{key:'notes',label:'Notes / next step',type:'textarea'}];
 return <><PageTitle eyebrow="ONE MILESTONE AT A TIME" title="IB tracker" description="Your own IA, Extended Essay, TOK and CAS milestones. Confirm requirements and dates with your school." action={<button className="primary" onClick={()=>setEditing({area:area==='All'?'IA':area,status:'Not started',title:''})}>Add milestone</button>}/><Stats items={['IA','Extended Essay','TOK','CAS'].map(type=>[type,`${life.ib.filter(x=>x.area===type&&x.status==='Done').length}/${life.ib.filter(x=>x.area===type).length} done`])}/><div className="life-filter" aria-label="Filter components">{['All','IA','Extended Essay','TOK','CAS'].map(type=><button aria-pressed={area===type} className={area===type?'active':''} onClick={()=>setArea(type)} key={type}>{type}</button>)}</div>{editing&&<Editor key={editing.id||'new'} fields={fields} initial={editing} onCancel={()=>setEditing(null)} onSave={f=>{update(v=>({...v,ib:upsert(v.ib,f)}));setEditing(null);}}/>}<div className="life-record-grid">{entries.sort((a,b)=>(a.due||'9999').localeCompare(b.due||'9999')).map(entry=><article className="life-card" key={entry.id}><span className="life-tag">{entry.area} {entry.subject&&'· '+entry.subject}</span><h2>{entry.title}</h2><p className={entry.due&&entry.due<today&&entry.status!=='Done'?'life-error':'life-muted'}>{entry.due?'Due '+entry.due:'No deadline set'}{entry.due&&entry.due<today&&entry.status!=='Done'?' · Overdue':''}</p><label className="life-inline-label">Progress<select value={entry.status} onChange={e=>{const status=e.target.value;update(v=>({...v,ib:v.ib.map(x=>x.id===entry.id?{...x,status}:x)}));}}>{statuses.map(status=><option key={status}>{status}</option>)}</select></label>{entry.notes&&<p className="life-notes">{entry.notes}</p>}{entry.evidence&&/^https?:\/\//i.test(entry.evidence)&&<a href={entry.evidence} target="_blank" rel="noreferrer">Open evidence</a>}<RecordActions label={entry.title} onEdit={()=>setEditing(entry)} onDelete={()=>update(v=>({...v,ib:v.ib.filter(x=>x.id!==entry.id)}))}/></article>)}</div>{!entries.length&&<Empty>Add your next concrete milestone—for example, refine an IA question, review an EE draft, or record a CAS reflection.</Empty>}</>;
}
export function SoccerLog(){const [life,update]=useLife(),{school}=useWorkspace(),[editing,setEditing]=useState(null);const today=localDate(school.timezone);const week=life.soccer.filter(x=>x.date>=addDays(today,-6)&&x.date<=today);const accuracy=passingAccuracy(week);
 const fields=[{key:'date',label:'Date',type:'date',required:true},{key:'type',label:'Session',type:'select',options:['Practice','Match','Fitness']},{key:'minutes',label:'Minutes played / trained',type:'number',min:0,max:600,required:true},{key:'completed',label:'Completed passes',type:'number',min:0,max:1000},{key:'attempted',label:'Attempted passes',type:'number',min:0,max:1000},{key:'fitness',label:'Fitness measure (include units)'},{key:'reflection',label:'What went well? What needs work?',type:'textarea'},{key:'nextFocus',label:'Next session’s measurable focus'},{key:'planId',label:'Mark a planned block complete (optional)',type:'select',options:[['','No linked block'],...life.plans.filter(p=>p.kind==='soccer').map(p=>[p.id,p.date+' · '+p.title])]}];
 return <><PageTitle eyebrow="TRAIN. NOTICE. IMPROVE." title="Soccer performance" description="Keep a clear record of your minutes, passing, fitness and next focus." action={<button className="primary" onClick={()=>setEditing({date:today,type:'Practice',minutes:'',completed:'',attempted:'',planId:''})}>Log session</button>}/><Stats items={[["Sessions · last 7 days",week.length],["Minutes · last 7 days",week.reduce((n,l)=>n+Number(l.minutes||0),0)],["Pass accuracy · last 7 days",accuracy===null?'No data':accuracy+'%'],["Matches logged",life.soccer.filter(x=>x.type==='Match').length]]}/>{editing&&<Editor key={editing.id||'new'} initial={editing} fields={fields} validate={f=>Number(f.completed||0)>Number(f.attempted||0)?'Completed passes cannot exceed attempted passes.':f.date>today?'Log completed sessions here; use the weekly planner for future training.':null} onCancel={()=>setEditing(null)} onSave={f=>{update(v=>({...v,soccer:upsert(v.soccer,f),plans:f.planId?v.plans.map(p=>p.id===f.planId?{...p,done:true}:p):v.plans}));setEditing(null);}}/>}<div className="life-record-grid">{[...life.soccer].sort((a,b)=>b.date.localeCompare(a.date)).map(log=><article className="life-card" key={log.id}><span className="life-tag">{log.type} · {log.date}</span><h2>{log.minutes} minutes</h2><p>{Number(log.attempted)>0?`${log.completed||0}/${log.attempted} passes · ${Math.round(Number(log.completed||0)/Number(log.attempted)*100)}%`:'Passing not recorded'}</p>{log.fitness&&<p>Fitness: {log.fitness}</p>}<p className="life-notes">{log.reflection}</p>{log.nextFocus&&<div className="life-next"><b>Next focus</b><p>{log.nextFocus}</p></div>}<RecordActions label={log.type+' on '+log.date} onEdit={()=>setEditing(log)} onDelete={()=>update(v=>({...v,soccer:v.soccer.filter(x=>x.id!==log.id)}))}/></article>)}</div>{!life.soccer.length&&<Empty>Log your first practice or match. Only the numbers you enter are used in your statistics.</Empty>}</>;
}
export function Experiments(){const [life,update]=useLife(),[editing,setEditing]=useState(null);const fields=[{key:'title',label:'Business idea',required:true},{key:'customer',label:'Specific customer',required:true},{key:'assumption',label:'Riskiest assumption',type:'textarea',required:true},{key:'test',label:'How will you test it?',type:'textarea',required:true},{key:'success',label:'Success measure',required:true},{key:'deadline',label:'Review date',type:'date'},{key:'status',label:'Stage',type:'select',options:['Planned','Testing','Reviewed']},{key:'result',label:'Observed evidence / results',type:'textarea'},{key:'learning',label:'What did you learn?',type:'textarea'},{key:'decision',label:'Next decision',type:'select',options:['Undecided','Continue','Change approach','Stop']}];
 return <><PageTitle eyebrow="EVIDENCE BEFORE CONFIDENCE" title="Business experiments" description="Turn an idea into a test. Keep assumptions separate from results." action={<button className="primary" onClick={()=>setEditing({title:'',status:'Planned',decision:'Undecided'})}>New experiment</button>}/><Stats items={['Planned','Testing','Reviewed'].map(status=>[status,life.experiments.filter(x=>x.status===status).length])}/>{editing&&<Editor key={editing.id||'new'} initial={editing} fields={fields} onCancel={()=>setEditing(null)} onSave={f=>{update(v=>({...v,experiments:upsert(v.experiments,f)}));setEditing(null);}}/>}<div className="life-record-grid">{life.experiments.map(experiment=><article className="life-card" key={experiment.id}><span className="life-tag">{experiment.status}{experiment.deadline?' · Review '+experiment.deadline:''}</span><h2>{experiment.title}</h2><p className="life-muted">Customer: {experiment.customer}</p><dl className="life-definition">{[['Assumption',experiment.assumption],['Test',experiment.test],['Success measure',experiment.success],['Evidence',experiment.result||'Not recorded'],['Learning',experiment.learning||'Not recorded'],['Decision',experiment.decision]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><RecordActions label={experiment.title} onEdit={()=>setEditing(experiment)} onDelete={()=>update(v=>({...v,experiments:v.experiments.filter(x=>x.id!==experiment.id)}))}/></article>)}</div>{!life.experiments.length&&<Empty>Start with one idea and one risky assumption. Choose a measurable test before collecting results.</Empty>}</>;
}
