import test from 'node:test';
import assert from 'node:assert/strict';
import {dispatch,toolsList} from '../lib/chatgpt/protocol.js';
import {normalizeTask,syncPrompt,coachPrompt} from '../lib/chatgpt/model.js';
import {AI_CONFIGS} from '../lib/ai/configs.js';
test('MCP discovery reveals no user data; anonymous calls cannot run handlers',async()=>{let calls=0;const handlers={tusk_sync_status:async()=>{calls++;return {available:true};}};const discover=await dispatch({jsonrpc:'2.0',id:1,method:'tools/list'},null,handlers);assert.equal(discover.result.tools.length,5);const denied=await dispatch({jsonrpc:'2.0',id:2,method:'tools/call',params:{name:'tusk_sync_status'}},null,handlers);assert.equal(denied.error.code,-32001);assert.equal(calls,0);const allowed=await dispatch({jsonrpc:'2.0',id:3,method:'tools/call',params:{name:'tusk_sync_status'}},'verified-user',handlers);assert.equal(allowed.result.structuredContent.available,true);assert.equal(calls,1);});
test('MCP initializes statelessly, accepts notifications, and reports handler errors',async()=>{const init=await dispatch({jsonrpc:'2.0',id:1,method:'initialize',params:{protocolVersion:'2025-06-18'}},null,{});assert.equal(init.result.protocolVersion,'2025-06-18');assert.equal(await dispatch({jsonrpc:'2.0',method:'notifications/initialized'},null,{}),null);const failure=await dispatch({jsonrpc:'2.0',id:2,method:'tools/call',params:{name:'tusk_save_tasks'}},'user',{tusk_save_tasks:async()=>{throw new Error('Could not save');}});assert.equal(failure.result.isError,true);assert.match(failure.result.content[0].text,/Could not save/);assert.equal(toolsList.find(t=>t.name==='tusk_save_tasks').annotations.idempotentHint,true);});
test('task validation rejects invented source links and invalid dates; identity ignores digest message changes',async()=>{const input={title:'Coastal project',subject:'Geography',source_message_id:'actual_message_1',date:'2026-10-08',time:'09:30'};const a=await normalizeTask('school',input);const b=await normalizeTask('school',{...input,source_message_id:'actual_message_2',date:'2026-10-09'});assert.equal(a.id,b.id);assert.equal(a.source_url,'https://mail.google.com/mail/u/0/#all/actual_message_1');await assert.rejects(()=>normalizeTask('school',{...input,date:'2026-02-30'}));await assert.rejects(()=>normalizeTask('school',{...input,source_message_id:'https://example.com'}));await assert.rejects(()=>normalizeTask('school',{...input,date:'',time:'09:30'}));assert.equal((await normalizeTask('school',{...input,date:'',time:''})).date,'');});
test('handoffs exclude health from overall sync and retain coach-specific requests',()=>{assert.match(syncPrompt('all'),/Do not read or import health/);assert.match(syncPrompt('health'),/explicitly requesting health/);assert.match(coachPrompt(AI_CONFIGS.sports,'Improve my passing'),/coach="sports"/);assert.match(coachPrompt(AI_CONFIGS.school,'Plan my week'),/IB Coach/);});
