import test from 'node:test';
import assert from 'node:assert/strict';
import {random,seal,unseal} from '../lib/google/crypto.js';
import {extractCandidates,mergeSchool,calendarEvent,validDate} from '../lib/google/extract.js';
test('encrypted credentials cannot be decrypted for another user or purpose',async()=>{const key=random();const encrypted=await seal(key,'alice:token',{refresh_token:'fixture'});assert(!encrypted.includes('fixture'));assert.equal((await unseal(key,'alice:token',encrypted)).refresh_token,'fixture');await assert.rejects(()=>unseal(key,'bob:token',encrypted));await assert.rejects(()=>unseal(key,'alice:config',encrypted));});
const mail=(html,subject='ManageBac digest')=>({id:'fixture-message',internalDate:String(Date.UTC(2026,9,5)),payload:{headers:[{name:'Subject',value:subject},{name:'From',value:'notifications@managebac.com'}],body:{data:Buffer.from(html).toString('base64url')}}});
test('digest extracts upcoming deadlines and excludes graded tasks',async()=>{const html='<h3>Geography</h3><h3>Upcoming Tasks and Deadlines</h3><table class="class-digest"><tr><td><div class="month">Oct</div><div class="day">8</div></td><td><div class="title"><a>Coastal project</a></div>Thursday at 9:30 AM</td></tr></table><h3>Graded Tasks</h3><table class="graded-tasks"><tr><td><div class="title">Old essay</div>Oct 2</td></tr></table>';const result=await extractCandidates(mail(html),'school');assert.equal(result.length,1);assert.equal(result[0].title,'Coastal project');assert.equal(result[0].subject,'Geography');assert.equal(result[0].date,'2026-10-08');assert.equal(result[0].time,'09:30');});
test('generic emails do not invent deadlines and imports preserve manual edits',async()=>{const candidates=await extractCandidates(mail('Please complete this task','New task'),'business');assert.equal(candidates[0].date,'');const candidate={...candidates[0],sector:'school',type:'assignment',date:'2026-10-09'};const first=mergeSchool({},[candidate]);first.assignments[0].title='My edited title';const again=mergeSchool(first,[candidate]);assert.equal(again.assignments.length,1);assert.equal(again.assignments[0].title,'My edited title');});
test('calendar IDs are stable, account scoped and dates are validated',async()=>{const item={key:'assignment-a',title:'Task',date:'2026-12-31',time:'23:55'};const a=await calendarEvent('alice',item,'America/Nassau');assert.equal(a.id,(await calendarEvent('alice',item,'America/Nassau')).id);assert.notEqual(a.id,(await calendarEvent('bob',item,'America/Nassau')).id);assert.match(a.id,/^[a-v0-9]+$/);assert.equal(a.end.dateTime,'2027-01-01T00:10:00');assert.equal(validDate('2026-02-30'),false);await assert.rejects(()=>calendarEvent('alice',{...item,date:'2026-02-30'},'UTC'));assert.equal((await calendarEvent('alice',{...item,time:''},'UTC')).end.date,'2027-01-01');});
