import {hash,unb64} from './crypto.js';
export const textOnly=value=>String(value||'').replace(/<style[\s\S]*?<\/style>|<script[\s\S]*?<\/script>/gi,'').replace(/<[^>]*>/g,' ').replace(/&nbsp;|&#160;/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/\s+/g,' ').trim();
export function messageBody(payload){if(payload?.body?.data)return new TextDecoder().decode(unb64(payload.body.data));const parts=payload?.parts||[];return parts.filter(p=>p.mimeType==='text/html').map(messageBody).join('\n')||parts.map(messageBody).join('\n');}
export function validDate(value){return /^\d{4}-\d{2}-\d{2}$/.test(value||'')&&!Number.isNaN(Date.parse(value+'T12:00:00Z'))&&new Date(value+'T12:00:00Z').toISOString().slice(0,10)===value;}
const months=['jan','feb','mar','apr','may','jun','jul','aug','sep','oct','nov','dec'];
export function extractDeadline(text,received){const m=text.match(/\b(January|February|March|April|May|June|July|August|September|October|November|December|Jan|Feb|Mar|Apr|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s+(\d{1,2})(?:,?\s+(20\d{2}))?(?:\s+(?:at\s+)?(\d{1,2}):(\d{2})\s*(AM|PM))?/i);if(!m)return {date:'',time:''};const month=months.indexOf(m[1].slice(0,3).toLowerCase())+1;let year=m[3]?Number(m[3]):received.getUTCFullYear();if(!m[3]&&received.getUTCMonth()===11&&month===1)year++;const date=`${year}-${String(month).padStart(2,'0')}-${m[2].padStart(2,'0')}`;let time='';const tm=text.match(/\b(\d{1,2}):(\d{2})\s*(AM|PM)\b/i);if(tm&&Number(tm[1])>=1&&Number(tm[1])<=12&&Number(tm[2])<60)time=String(Number(tm[1])%12+(tm[3].toUpperCase()==='PM'?12:0)).padStart(2,'0')+':'+tm[2];return {date:validDate(date)?date:'',time};}
export async function extractCandidates(message,sector){const headers=message.payload?.headers||[];const subject=headers.find(h=>h.name.toLowerCase()==='subject')?.value||'Email follow-up';const html=messageBody(message.payload);const received=new Date(Number(message.internalDate)||Date.now());const candidates=[];const add=async(title,body,course='',dates={date:'',time:''})=>{title=textOnly(title).slice(0,200);if(!title)return;const sourceKey=await hash(sector+':'+course.toLowerCase()+':'+title.toLowerCase());candidates.push({id:sourceKey,sector,title,subject:course,date:dates.date,time:dates.time,type:/\b(test|exam|quiz|summative)\b/i.test(title)?'test':'assignment',excerpt:textOnly(body).slice(0,600),source_message_id:message.id,source_url:'https://mail.google.com/mail/u/0/#all/'+message.id});};
 if(sector==='school'&&/managebac/i.test(subject+' '+headers.find(h=>h.name.toLowerCase()==='from')?.value+' '+html)){
  // Only upcoming digest tables: graded work is never imported as a new task.
  const tables=[...html.matchAll(/<table\b[^>]*class=["'][^"']*class-digest[^"']*["'][^>]*>([\s\S]*?)<\/table>/gi)];
  for(const table of tables){const before=html.slice(0,table.index);const headings=[...before.matchAll(/<h[23]\b[^>]*>([\s\S]*?)<\/h[23]>/gi)].map(m=>textOnly(m[1])).filter(h=>!/(upcoming|graded|tasks and deadlines)/i.test(h));const course=headings.at(-1)||'';for(const row of table[1].matchAll(/<tr\b[^>]*>([\s\S]*?)<\/tr>/gi)){const title=row[1].match(/class=["'][^"']*\btitle\b[^"']*["'][^>]*>([\s\S]*?)<\/div>/i)?.[1];if(title)await add(title,row[1],course,extractDeadline(textOnly(row[1]),received));}}
  if(!tables.length&&!/digest/i.test(subject)){const body=textOnly(html);const when=body.match(/\b(?:When|Due(?: date)?)\s*:\s*(.{0,90})/i);await add(subject,body,'',when?extractDeadline(when[1],received):{date:'',time:''});}
 }else await add(subject,message.snippet||html);
 return candidates;
}
export function mergeSchool(current,candidates){const value={...(current||{})};value.assignments=[...(value.assignments||[])];value.tests=[...(value.tests||[])];const existing=new Set([...value.assignments,...value.tests].map(t=>t.sync_key));for(const c of candidates){if(existing.has(c.id))continue;const common={id:'mail_'+c.id.slice(0,24),sync_key:c.id,title:c.title,subject:c.subject||'General',description:c.excerpt||'',source:'gmail',source_message_id:c.source_message_id,source_url:c.source_url,priority:'medium',created_at:new Date().toISOString(),updated_at:new Date().toISOString(),manual_overrides:{},calendar_event_id:c.calendar_event_id||null};if(c.type==='test')value.tests.push({...common,date:c.date,time:c.time,topics:[],questionLog:[],reminder:'1 day before'});else value.assignments.push({...common,due_date:c.date,due_time:c.time,status:'upcoming',progress_percentage:0});existing.add(c.id);}return value;}
export async function calendarEvent(user,item,timezone){if(!validDate(item.date))throw new Error('Review the task date first.');if(item.time&&!/^([01]\d|2[0-3]):[0-5]\d$/.test(item.time))throw new Error('Review the task time first.');try{new Intl.DateTimeFormat('en',{timeZone:timezone});}catch{throw new Error('Choose a valid school timezone.');}const key=await hash(user+':'+item.key);const next=new Date(item.date+'T'+(item.time||'00:00')+':00Z');next.setUTCMinutes(next.getUTCMinutes()+(item.time?15:1440));return {id:'tusk'+key,summary:(item.subject?item.subject+' — ':'')+item.title,description:[item.description,'Tusk deadline reminder. Timed reminders last 15 minutes; this is not the duration of the class or test.'].filter(Boolean).join('\n'),start:item.time?{dateTime:item.date+'T'+item.time+':00',timeZone:timezone}:{date:item.date},end:item.time?{dateTime:next.toISOString().slice(0,19),timeZone:timezone}:{date:next.toISOString().slice(0,10)},extendedProperties:{private:{tuskKey:key}}};}
