'use client';
import {useEffect,useRef,useState} from 'react';
import {Mic,Square} from 'lucide-react';
export function VoiceInput({onTranscript,disabled=false}){
 const [supported,setSupported]=useState(false),[listening,setListening]=useState(false),[interim,setInterim]=useState(''),[error,setError]=useState('');const active=useRef(null),callback=useRef(onTranscript);callback.current=onTranscript;
 useEffect(()=>{setSupported(!!(window.SpeechRecognition||window.webkitSpeechRecognition));const stop=()=>{active.current?.abort();};const visibility=()=>{if(document.hidden)stop();};document.addEventListener('visibilitychange',visibility);return()=>{document.removeEventListener('visibilitychange',visibility);const r=active.current;if(r){r.onresult=null;r.onerror=null;r.onend=null;r.abort();}active.current=null;};},[]);
 function start(){if(active.current||disabled)return;setError('');setInterim('');const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition)return;const r=new Recognition();active.current=r;r.lang='en-US';r.continuous=false;r.interimResults=true;r.onresult=e=>{let partial='';for(let i=e.resultIndex;i<e.results.length;i++){const value=e.results[i][0].transcript;if(e.results[i].isFinal)callback.current(value);else partial+=value;}setInterim(partial);};r.onend=()=>{active.current=null;setListening(false);setInterim('');};r.onerror=e=>{if(e.error!=='aborted')setError(e.error==='not-allowed'||e.error==='service-not-allowed'?'Microphone access was blocked. Open Tusk in a browser tab and allow microphone access, or type your question.':e.error==='no-speech'?'No speech detected. Try again.':'Voice input is unavailable right now. Please type your question.');};try{r.start();setListening(true);}catch{active.current=null;setListening(false);setError('Could not start the microphone. Please type your question.');}}
 return <div className="tusk-voice"><button type="button" className="tusk-sync-button" disabled={!supported||disabled} aria-pressed={listening} onClick={()=>listening?active.current?.stop():start()}>{listening?<Square size={16}/>:<Mic size={16}/>} {listening?'Stop dictation':'Dictate question'}</button><span role="status">{listening?'Listening… '+interim:!supported?'Voice input is not supported here. You can use your keyboard’s microphone or type.':'Review your words before continuing.'}</span>{error&&<p role="alert">{error}</p>}<small>Your browser may send audio to its speech service. Tusk does not store audio. Nothing is submitted automatically.</small></div>;
}
